//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nansbook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deduction
    {
        public int Id { get; set; }
        public int UserXStoreId { get; set; }
        public Nullable<decimal> FixedAmtPerSvcSale { get; set; }
        public Nullable<int> PctPerSvcSale { get; set; }
        public Nullable<int> PctTotAllSvcSales { get; set; }
        public Nullable<decimal> DailyAmt { get; set; }
        public Nullable<decimal> DailyCleaningExp { get; set; }
        public Nullable<int> DailyCleaningExpWkday { get; set; }
        public Nullable<int> TipProcessingPct { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual UserXStore UserXStore { get; set; }
    }
}
