//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nansbook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseCategory
    {
        public ExpenseCategory()
        {
            this.Expenses = new HashSet<Expense>();
            this.ExpenseCategory1 = new HashSet<ExpenseCategory>();
        }
    
        public int Id { get; set; }
        public int UserXStoreId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual ICollection<Expense> Expenses { get; set; }
        public virtual UserXStore UserXStore { get; set; }
        public virtual ICollection<ExpenseCategory> ExpenseCategory1 { get; set; }
        public virtual ExpenseCategory ExpenseCategory2 { get; set; }
    }
}
