//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nansbook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.Discounts = new HashSet<Discount>();
            this.Sales = new HashSet<Sale>();
            this.Service1 = new HashSet<Service>();
        }
    
        public int Id { get; set; }
        public int UserXStoreId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual ICollection<Discount> Discounts { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual ICollection<Service> Service1 { get; set; }
        public virtual Service Service2 { get; set; }
        public virtual UserXStore UserXStore { get; set; }
    }
}
