//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nansbook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserXStore
    {
        public UserXStore()
        {
            this.AppSettings = new HashSet<AppSetting>();
            this.CommissionRates = new HashSet<CommissionRate>();
            this.Deductions = new HashSet<Deduction>();
            this.Discounts = new HashSet<Discount>();
            this.Expenses = new HashSet<Expense>();
            this.ExpenseCategories = new HashSet<ExpenseCategory>();
            this.GiftCards = new HashSet<GiftCard>();
            this.Notifications = new HashSet<Notification>();
            this.Paychecks = new HashSet<Paycheck>();
            this.PaymentMethods = new HashSet<PaymentMethod>();
            this.Products = new HashSet<Product>();
            this.Salaries = new HashSet<Salary>();
            this.Sales = new HashSet<Sale>();
            this.Services = new HashSet<Service>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int StoreId { get; set; }
        public bool Current { get; set; }
    
        public virtual ICollection<AppSetting> AppSettings { get; set; }
        public virtual ICollection<CommissionRate> CommissionRates { get; set; }
        public virtual ICollection<Deduction> Deductions { get; set; }
        public virtual ICollection<Discount> Discounts { get; set; }
        public virtual ICollection<Expense> Expenses { get; set; }
        public virtual ICollection<ExpenseCategory> ExpenseCategories { get; set; }
        public virtual ICollection<GiftCard> GiftCards { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Paycheck> Paychecks { get; set; }
        public virtual ICollection<PaymentMethod> PaymentMethods { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Salary> Salaries { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual ICollection<Service> Services { get; set; }
        public virtual Store Store { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
