//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nansbook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Category1 = new HashSet<Category>();
            this.Category11 = new HashSet<Category>();
            this.Category12 = new HashSet<Category>();
            this.SalesEntries = new HashSet<SalesEntry>();
            this.SalesEntries1 = new HashSet<SalesEntry>();
            this.SalesEntries2 = new HashSet<SalesEntry>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int CategoryType { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Percentage { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedById { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
        public virtual ICollection<Category> Category1 { get; set; }
        public virtual Category Category2 { get; set; }
        public virtual CategoryType CategoryType1 { get; set; }
        public virtual ICollection<Category> Category11 { get; set; }
        public virtual Category Category3 { get; set; }
        public virtual ICollection<Category> Category12 { get; set; }
        public virtual Category Category4 { get; set; }
        public virtual ICollection<SalesEntry> SalesEntries { get; set; }
        public virtual ICollection<SalesEntry> SalesEntries1 { get; set; }
        public virtual ICollection<SalesEntry> SalesEntries2 { get; set; }
    }
}
