//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nansbook
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesEntry
    {
        public int Id { get; set; }
        public int TechnicianId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public decimal SaleAmt { get; set; }
        public Nullable<decimal> TipAmt { get; set; }
        public Nullable<decimal> DeductionAmt { get; set; }
        public Nullable<int> DiscountCategoryId { get; set; }
        public System.DateTime TimeOfSale { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedById { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
        public virtual UserProfile UserProfile2 { get; set; }
        public virtual Category Category { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual Category Category2 { get; set; }
    }
}
