//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nansbook
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityQuestion
    {
        public SecurityQuestion()
        {
            this.UserProfiles = new HashSet<UserProfile>();
            this.UserProfiles1 = new HashSet<UserProfile>();
            this.UserProfiles2 = new HashSet<UserProfile>();
        }
    
        public int Id { get; set; }
        public string Question { get; set; }
    
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
        public virtual ICollection<UserProfile> UserProfiles1 { get; set; }
        public virtual ICollection<UserProfile> UserProfiles2 { get; set; }
    }
}
